In [1]:
import numpy as np 
import numpy.linalg as la 
import qutip

import matplotlib.pyplot as plt

In [164]:
d=2; L=6; max_bond=4 #maximum bond dimension allowed
random_state=np.random.rand(d**L, 1)
GHZ_state=np.array([1.]+[0. for i in range(0,d**L - 2)] + [1.])
matrix_Psi=np.reshape(random_state, (d, d**(L-1)))

In [165]:
def true_Singular(original_S, dims):
    true_S=np.zeros(dims)
    true_S[:original_S.size, :original_S.size]=np.diag(original_S)
    return true_S

In [166]:
matrix_Psi.shape

(2, 32)

In [167]:
first_MPS_matrix, first_S, first_Vh=la.svd(matrix_Psi)
first_S=true_Singular(first_S, dims=(first_MPS_matrix.shape[1], first_Vh.shape[0]))
first_Vh=np.reshape(first_true_s@first_Vh, (len(first_S)*d, d**(L-2)))
print(first_MPS_matrix.shape, first_Vh.shape)

(2, 2) (4, 16)


In [168]:
second_MPS_matrix, second_S, second_Vh=la.svd(first_Vh)
second_S=true_Singular(second_S, dims=(second_MPS_matrix.shape[1], second_Vh.shape[0]))
second_Vh=np.reshape(second_S@second_Vh, (len(second_S)*d, d**(L-3)))
second_MPS_matrix=np.reshape(second_MPS_matrix, (d, len(first_S)*len(second_S)))
print(second_MPS_matrix.shape, second_Vh.shape)

(2, 8) (8, 8)


In [170]:
third_MPS_matrix, third_S, third_Vh=la.svd(second_Vh)
third_S=true_Singular(third_S, dims=(third_MPS_matrix.shape[1], third_Vh.shape[0]))
third_Vh=np.reshape(third_S@third_Vh, (len(third_S)*d, d**(L-4)))
third_MPS_matrix=np.reshape(third_MPS_matrix, (len(first_S)*len(second_S), len(first_S)*len(second_S)))
print(third_MPS_matrix.shape, third_Vh.shape)

(8, 8) (16, 4)


In [177]:
fourth_MPS_matrix, fourth_S, fourth_Vh=la.svd(third_Vh)
fourth_S=true_Singular(fourth_S, dims=(fourth_MPS_matrix.shape[1], fourth_Vh.shape[0]))
fourth_Vh=np.reshape(fourth_S@fourth_Vh, (len(fourth_S)*d, d**(L-5)))
fourth_MPS_matrix=fourth_MPS_matrix[np.ix_([i for i in range(0, d**(L-3))],[0,1])]
print(fourth_MPS_matrix.shape, fourth_Vh.shape)

(8, 2) (32, 2)


In [172]:
fifth_MPS_matrix, fifth_S, fifth_Vh=la.svd(fourth_Vh)
fifth_S=true_Singular(fifth_S, dims=(fifth_MPS_matrix.shape[1], fifth_Vh.shape[0]))
fifth_MPS_matrix=fourth_MPS_matrix[np.ix_([0,1],[0,1])]
fifth_Vh=fifth_S@fifth_Vh
print(fifth_MPS_matrix.shape, fifth_Vh.shape)

(2, 2) (32, 2)


In [173]:
third_S

array([[3.90702621, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 1.61452774, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.01800462, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.75112201, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.62638827,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.46718354, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.31328726, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.11409064]])

In [175]:
(first_MPS_matrix@second_MPS_matrix@third_MPS_matrix@fourth_MPS_matrix@fifth_MPS_matrix).trace()

-0.6284219561921265

In [49]:
fourth_MPS_matrix[:8][:8]

array([[-0.64953269, -0.16562442,  0.02798412,  0.2949868 , -0.09266492,
         0.21574537,  0.49695832,  0.19554398,  0.24793258,  0.06998846,
         0.01654321,  0.2070625 ,  0.02799267, -0.09641161, -0.03969656,
         0.03695305],
       [-0.72007141,  0.08794496, -0.06554541, -0.19878013, -0.02595294,
         0.03920748, -0.55132332, -0.20726652, -0.18795988,  0.05138094,
         0.04841396, -0.16845895, -0.04015222,  0.10039119,  0.01344646,
        -0.01621337],
       [ 0.14207655, -0.17656685, -0.45196934, -0.03021406,  0.27540468,
         0.36959508, -0.01773528, -0.26982867,  0.13665289,  0.56079243,
         0.34093837,  0.02070139,  0.02360443, -0.04632526, -0.06617834,
         0.03108797],
       [-0.10891628,  0.72500817, -0.03470797, -0.15829615,  0.58306811,
         0.00768869,  0.20643415,  0.15750591, -0.00160069,  0.05998656,
        -0.1024187 ,  0.00839367, -0.01251944, -0.11684555, -0.02846675,
         0.00253151],
       [-0.10317615, -0.57610253, -0

In [40]:
anp.reshape(fourth_MPS_matrix, (8,2))

ValueError: cannot reshape array of size 256 into shape (8,2)

In [33]:
third_MPS_matrix.shape

(8, 8)

In [24]:
(len(third_S)*d, d**(L-3))

(16, 8)

In [6]:
third_MPS_matrix, third_S, third_Vh=la.svd(second_Vh)
third_Vh=np.diag(third_S)@third_Vh
third´´´´_Vh.shape

SyntaxError: invalid character '´' (U+00B4) (2382889492.py, line 3)

In [ ]:
fourth_MPS_matrix, fourth_S, fourth_Vh=la.svd(third_Vh)
fourth_Vh=np.reshape(np.diag(fourth_S)@fourth_Vh, (len(fourth_S)*d, d**(L-4)))
fourth_Vh.shape

In [160]:
fifth_MPS_matrix, fifth_S, fifth_Vh=la.svd(fourth_Vh)
fifth_Vh=np.reshape(np.diag(fifth_S)@fifth_Vh, (len(fifth_S)*d, d**(L-5)))
fifth_Vh.shape

(8, 2)

In [154]:
(len(fourth_S)*d, d**(L-4))

(16, 4)

In [137]:
fourth_MPS_matrix, fourth_S, fourth_Vh=la.svd(third_Vh)
fourth_true_s=np.zeros((fourth_MPS_matrix.shape[1], fourth_Vh.shape[0]))
fourth_true_s[:fourth_S.size, :fourth_S.size]=np.diag(fourth_S)
fourth_Vh=np.reshape(fourth_true_s@fourth_Vh, (d*len(fourth_S), d**(L-4)))
fourth_MPS_matrix.shape

(8, 8)

In [147]:
fourth_Vh.shape

(16, 4)

In [142]:
fifth_MPS_matrix, fifth_S, fifth_Vh=la.svd(fourth_Vh)
fifth_true_s=np.zeros((fifth_MPS_matrix.shape[1], fifth_Vh.shape[0]))
fifth_true_s[:fifth_S.size, :fifth_S.size]=np.diag(fifth_S)
fifth_Vh=np.reshape(fifth_true_s@fifth_Vh, (d*len(fifth_S), d**(L-5)))

ValueError: cannot reshape array of size 64 into shape (8,2)

In [145]:
fifth_S

array([3.39721768, 1.3834625 , 1.23849509, 0.85404728])

In [146]:
fifth_MPS_matrix.shape

(16, 16)

In [144]:
(d*len(fifth_S), d**(L-5))

(8, 2)