In [41]:
import numpy as np

def swap_tensor_identity(state, indices, phys_dim):
    state = np.array(state)
    
    n = state.size // 2
    if len(indices) != 2:
        raise ValueError("Exactly two indices must be provided.")
    
    i, j = indices; d=phys_dim
    if i >= n or j >= n or i < 0 or j < 0:
        raise ValueError("Indices must be within the dimensions of the state.")

    swapped_state = np.zeros_like(state)

    # Perform the SWAP * Identity operation
    for k in range(n):
        # Copy the second part of the pairs unchanged
        swapped_state[d*k+1] = state[d*k+1]  # Second indices remain the same
        
        if k == i:
            swapped_state[d*i] = state[d*j]  # Swap first part of i with j
        elif k == j:
            swapped_state[d*j] = state[d*i]  # Swap first part of j with i
        else:
            swapped_state[d*k] = state[d*k]  # Keep other first parts unchanged
            
    return swapped_state

# Example usage
state = np.array([1, 10, 2, 20, 3, 30, 4, 40])  # |00|01|00>
swapped_state = swap_tensor_identity(state, (0, 1), d)
print(state)
print(swapped_state) 

[ 1 10  2 20  3 30  4 40]
[ 2 10  1 20  3 30  4 40]


In [17]:
N=4 # number of copies 
d=2 # internal dimensionality of the system

Phi_plus=np.array([ [np.random.rand() for i in range(-1,d-1)] for j in range(N)])

In [18]:
Phi_plus

array([[0.49956873, 0.4040745 ],
       [0.87829859, 0.26140389],
       [0.17921457, 0.05301662],
       [0.35465452, 0.00362765]])

In [20]:
Phi_plus=SWAPed(Phi_plus, (0,1))
Phi_plus

array([[0.49956873, 0.4040745 ],
       [0.87829859, 0.26140389],
       [0.87829859, 0.26140389],
       [0.35465452, 0.00362765]])